version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"

  php-fpm:
    container_name: api.casher.dev
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www

  database:
    container_name: db.casher.dev
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    restart: unless-stopped